[package]
name = "vault_manager"
type = "contract"
authors = ["Aztec Liquid Staking"]
compiler_version = ">=0.30.0"
edition = "2024.01"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v2.1.9", directory = "noir-projects/aztec-nr/aztec" }
