[package]
name = "staking_pool"
type = "contract"
authors = ["Aztec Liquid Staking"]
compiler_version = ">=0.30.0"
edition = "2024.01"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.66.0", directory = "noir-projects/aztec-nr/aztec" }
